import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Navbar } from "@/components/layout/navbar"
import { GradientCard } from "@/components/ui/gradient-card"
import { Code, Cpu, Users } from "lucide-react"

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1">
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  <span className="text-gradient">DevQuizBattle</span>
                </h1>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  Test your coding knowledge in real-time multiplayer battles with AI-generated questions
                </p>
              </div>
              <div className="flex flex-col sm:flex-row gap-4">
                <Button asChild size="lg">
                  <Link href="/dashboard">Start Playing</Link>
                </Button>
                <Button variant="outline" size="lg" asChild>
                  <Link href="/login">Sign In</Link>
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section className="py-12 md:py-24 lg:py-32 bg-muted/50">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-3 lg:gap-12">
              <GradientCard>
                <div className="flex flex-col items-center space-y-4">
                  <div className="inline-block rounded-full bg-primary/10 p-3">
                    <Code className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-xl font-bold">Coding Challenges</h3>
                  <p className="text-muted-foreground text-center">
                    Test your skills with language-specific coding questions across multiple difficulty levels
                  </p>
                </div>
              </GradientCard>
              <GradientCard>
                <div className="flex flex-col items-center space-y-4">
                  <div className="inline-block rounded-full bg-primary/10 p-3">
                    <Cpu className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-xl font-bold">AI-Generated Questions</h3>
                  <p className="text-muted-foreground text-center">
                    Unique questions generated by AI ensure fresh challenges every time you play
                  </p>
                </div>
              </GradientCard>
              <GradientCard>
                <div className="flex flex-col items-center space-y-4">
                  <div className="inline-block rounded-full bg-primary/10 p-3">
                    <Users className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-xl font-bold">Multiplayer Battles</h3>
                  <p className="text-muted-foreground text-center">
                    Compete with friends in real-time to see who can answer questions the fastest
                  </p>
                </div>
              </GradientCard>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t py-6 md:py-0">
        <div className="container flex flex-col items-center justify-between gap-4 md:h-16 md:flex-row">
          <p className="text-sm text-muted-foreground">
            &copy; {new Date().getFullYear()} DevQuizBattle. All rights reserved.
          </p>
          <div className="flex items-center gap-4 text-sm text-muted-foreground">
            <Link href="/privacy" className="hover:underline">
              Privacy
            </Link>
            <Link href="/terms" className="hover:underline">
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
