"use client";

import { Navbar } from "@/components/layout/navbar";
import { Button } from "@/components/ui/button";
import {
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { GradientCard } from "@/components/ui/gradient-card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useSupabase } from "@/lib/supabase-provider";
import { Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";

export default function DashboardPage() {
  const { user, supabase, loading: authLoading } = useSupabase();
  const router = useRouter();
  const [gameCode, setGameCode] = useState("");
  const [maxPlayers, setMaxPlayers] = useState(4);
  const [loading, setLoading] = useState(false);

  // Redirect to login if not authenticated
  if (!authLoading && !user) {
    router.push("/login");
    return null;
  }

  // Add this function at the top of the component, before the handleCreateGame function
  const ensureUserProfile = async () => {
    if (!user) return false;

    // Check if profile exists
    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("*")
      .eq("id", user.id)
      .single();

    if (profileError) {
      // Profile doesn't exist, create it
      const username =
        user.email?.split("@")[0] ||
        `user_${Math.random().toString(36).substring(2, 8)}`;

      const { error: insertError } = await supabase.from("profiles").insert({
        id: user.id,
        username: username,
      });

      if (insertError) {
        toast.error("Errore", {
          description: "Impossibile creare il profilo utente",
        });
        return false;
      }
    }

    return true;
  };

  // Modify the handleCreateGame function to ensure profile exists first
  const handleCreateGame = async () => {
    if (!user) return;

    setLoading(true);
    try {
      // Ensure user profile exists
      const profileExists = await ensureUserProfile();
      if (!profileExists) return;

      const { data, error } = await supabase
        .from("games")
        .insert({
          host_id: user.id,
          status: "waiting",
          max_players: maxPlayers,
          code: "", // Will be auto-generated by the trigger
        })
        .select()
        .single();

      if (error) throw error;

      // Add the host as the first player with turn_order 1
      const { error: playerError } = await supabase
        .from("game_players")
        .insert({
          game_id: data.id,
          player_id: user.id,
          turn_order: 1,
        });

      if (playerError) throw playerError;

      router.push(`/game/${data.code}`);
    } catch (error: any) {
      toast.error("Error", {
        description: error.message,
      });
    } finally {
      setLoading(false);
    }
  };

  // Also modify the handleJoinGame function to ensure profile exists first
  const handleJoinGame = async () => {
    if (!user || !gameCode) return;

    setLoading(true);
    try {
      // Ensure user profile exists
      const profileExists = await ensureUserProfile();
      if (!profileExists) return;

      // Find the game by code
      const { data: game, error: gameError } = await supabase
        .from("games")
        .select("*")
        .eq("code", gameCode.toUpperCase())
        .single();

      if (gameError) throw new Error("Game not found");

      if (game.status !== "waiting") {
        throw new Error("Game has already started");
      }

      // Check if player is already in the game
      const { data: existingPlayer, error: existingPlayerError } =
        await supabase
          .from("game_players")
          .select("*")
          .eq("game_id", game.id)
          .eq("player_id", user.id)
          .maybeSingle();

      if (!existingPlayerError && existingPlayer) {
        // Player is already in the game, just navigate there
        router.push(`/game/${gameCode}`);
        return;
      }

      // Count current players to determine turn order
      const { data: players, error: playersError } = await supabase
        .from("game_players")
        .select("*")
        .eq("game_id", game.id)
        .order("turn_order", { ascending: true });

      if (playersError) throw playersError;

      if (players.length >= game.max_players) {
        throw new Error("Game is full");
      }

      // Add player to the game with the next turn order
      const { error: joinError } = await supabase.from("game_players").insert({
        game_id: game.id,
        player_id: user.id,
        turn_order: players.length + 1,
      });

      if (joinError) throw joinError;

      router.push(`/game/${gameCode}`);
    } catch (error: any) {
      toast.error("Error", {
        description: error.message,
      });
    } finally {
      setLoading(false);
    }
  };

  if (authLoading) {
    return (
      <div className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex flex-1 justify-center items-center">
          <Loader2 className="w-8 h-8 animate-spin" />
        </main>
      </div>
    );
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 py-8 container">
        <h1 className="mb-8 font-bold text-3xl">
          <span className="text-gradient">Dashboard</span>
        </h1>

        <div className="gap-8 grid md:grid-cols-2">
          <GradientCard>
            <CardHeader>
              <CardTitle>Crea una nuova partita</CardTitle>
              <CardDescription>
                Imposta una nuova sfida di quiz di programmazione
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="max-players">
                    Numero massimo di giocatori
                  </Label>
                  <Input
                    id="max-players"
                    type="number"
                    min={2}
                    max={8}
                    value={maxPlayers}
                    onChange={(e) =>
                      setMaxPlayers(Number.parseInt(e.target.value))
                    }
                  />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button
                onClick={handleCreateGame}
                disabled={loading}
                className="w-full"
              >
                {loading ? (
                  <Loader2 className="mr-2 w-4 h-4 animate-spin" />
                ) : null}
                Crea partita
              </Button>
            </CardFooter>
          </GradientCard>

          <GradientCard>
            <CardHeader>
              <CardTitle>Unisciti a una partita</CardTitle>
              <CardDescription>
                Inserisci un codice partita per unirti a una partita esistente
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="game-code">Codice partita</Label>
                  <Input
                    id="game-code"
                    placeholder="Enter 6-digit code"
                    value={gameCode}
                    onChange={(e) => setGameCode(e.target.value.toUpperCase())}
                    maxLength={6}
                  />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button
                onClick={handleJoinGame}
                disabled={loading || !gameCode}
                className="w-full"
              >
                {loading ? (
                  <Loader2 className="mr-2 w-4 h-4 animate-spin" />
                ) : null}
                Unisciti
              </Button>
            </CardFooter>
          </GradientCard>
        </div>
      </main>
    </div>
  );
}
